### ISSUE TITLE
Why not publish to http://package.elm-lang.org/?

### ISSUE THREAD

**Issue by greyepoxy** [eeue56/servelm#4]
I suspect I am miss understanding something but why not publish this to http://package.elm-lang.org/?

If I wanted to try and use this the only option currently is to copy paste.

**Comment by fatso83** [comment]
Hey, just fork it and do it yourself. The license is MIT, so do whatever you please. The project is like 489 lines, so maintaining it seems reasonable.

**Comment by eeue56** [comment]
@fatso83 You seem to have a misunderstanding of how the Elm ecosystem works. This code requires Native code, and so cannot be published. this code is also out of date.
