### ISSUE TITLE
More explanation about why this package became depreciated

### ISSUE THREAD

**Issue by tomleo** [eeue56/servelm#6]
I'm new to elm and exploring what people have done with elm. As with most frameworks / front-end languages a Todo example is to be expected. However a back-end library built in a language designed for the front-end seems interesting (`node`...)

> Depreciated. Server side elm is not designed to work this way.

How should server side elm be designed? What things did this project get wrong?

**Comment by eeue56** [comment]
https://github.com/noredink/take-home#should-i-use-this-in-production

**Comment by tomleo** [comment]
Thanks!
